/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.view.comm {
    export class HomePageUI extends Laya.View {
		public banner:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("view/comm/HomePage");
        }
    }
    REG("ui.view.comm.HomePageUI",HomePageUI);
}